name: faui
description: Authentication UI for Flutter. Uses Firebase auth as security provider. The library provides UI to register user, validate email, sign in, sign out, restore password.
version: 1.0.6
author: Polina Cherkasova <polina.c@live.com>
homepage: https://github.com/polina-c/flutter-auth-ui

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  uuid: ^2.0.1
  crypted_preferences: ^0.0.2

dev_dependencies:
  test: any

flutter:
  uses-material-design: true
