# author: Polina Cherkasova <polina.c@live.com>

name: faui
description: Authentication UI for Flutter. Uses Firebase auth as security provider. The library provides UI to register user, validate email, sign in, sign out, restore password.
version: 2.0.14
homepage: https://github.com/polina-c/flutter-auth-ui

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  uuid: ^2.0.1
  shared_preferences: ^0.5.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
