name: faui
description: >
  Authentication UI and data access for Flutter. Uses Firebase auth as security provider.

version: 2.0.30
homepage: https://github.com/polina-c/flutter-auth-ui

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.8 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
  uuid: ^2.0.1
  shared_preferences: ^0.5.6

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
