name: faui_demo_2

environment:
  sdk: '>=2.3.0-dev.0.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # After copying this example out of 'faui', update path
  # or reference pub.dev:
  #
  # faui: <latest version>
  #
  # You can find latest version here: https://pub.dev/packages/faui 
  faui:
    path: ./../..

  http: ^0.12.0+2
  crypted_preferences: ^0.0.2
  uuid: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
